version: 2

run:
  timeout: 5m
  skip-dirs:
    - .git
    - bin
    - dist
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - gocritic
    - revive
    - stylecheck
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: test/
      linters:
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 